language: python
python:
- "3.6"

# command to install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls

# Run tests
script:
- pytest --cov=./app

branches:
 only:
  -develop
after_success:
- coveralls

