language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - pytest --cov=./app
branches:
  only:
    - develop
after_success:
  - coverall
  - codecov --token=b881209b-615a-4c5e-b670-3c5277f2f6fe
