language: python
python:
  - "3.6"

services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
  
before_script:
  - psql -c 'create database ireporter_test;' -U postgres
  - psql -c "CREATE USER bafiam_admin WITH PASSWORD 'bafiam';" -U postgres
script:
  - pytest --cov=./app
branches:
  only:
    - develop
after_success:
  - coverall
  - codecov --token=b881209b-615a-4c5e-b670-3c5277f2f6fe
